### PR TITLE
Behaviors!

### PR DESCRIPTION
**Pull request by jakemac53**

### CODE REVIEW

**Comment by sigmundch** [comment]
Looks good! To make it easier for me to see things clearly, I copied your PR into rietveld and added comments here: https://codereview.chromium.org/1290643006/

**Comment by jakemac53** [comment]
@sigmundch Update here, but I think you will have to push the changes to reitveld? I also fully flushed out the tests and fixed the js behavior properties issue.

**Comment by sigmundch** [comment]
added a few more nit comments, but otherwise lgtm

**Comment by jakemac53** [comment]
this has been merged into the behavior branch, closing

**Pull request closed without merging**
